title: Noah Peeters
email: noah@noahpeeters.de
description: >- # this means to ignore newlines until "baseurl:"
  My personal website about me and my projects.
baseurl: "/"
url: "https://www.noahpeeters.de"
breadcrumbs: true

twitter:
  username: noah_peeters

social:
  type: "Person"
  name: "Noah Peeters"
  links:
    - https://twitter.com/@noah_peeters
    - https://www.linkedin.com/in/noahpeeters
    - https://www.xing.com/profile/Noah_Peeters

author:
  name: "Noah N. Peeters"
  avatar: "/assets/images/profile.jpg"
  avatarfull: "/assets/images/profile_full.jpg"
  bio: "🌱 Vegan CS Student and iOS Developer"
  location: Geesthacht, Germany
  email: "noah@noahpeeters.de"
  github: "noahpeeters"
  keybase: "noahpeeters"
  linkedin: "noahpeeters"
  stackoverflow: "10961090/noah-peeters?tab=profile"
  twitter: "@noah_peeters"
  xing: "Noah_Peeters"
  links:
    - label: "Contact Form"
      icon: "far fa-fw fa-comment-alt"
      url: "/contact"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/491718952156"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/NoahPeeters"
    - label: "Apple Music"
      icon: "fas fa-fw fa-music"
      url: "https://music.apple.com/profile/noahpeeters"
    - label: "GPG Key"
      icon: "fas fa-fw fa-key"
      url: "/assets/files/Noah%20Noel%20Peeters%20(9E84A851)%20–%20Public.asc"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint"

search: true
search_full_content: true

bing_site_verification: BAD85875E61EAC15E60333093CFC4938
yandex_site_verification: 02fb0dc92e13682b

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from
  - jemoji

# sass
sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  ignore:
    envs: development

feed:
  path: /blog/feed.xml
  collections:
    news:
      path: /news/feed.xml

atom_feed:
  path: /blog/feed.xml

footer:
  links:
    - label: "Imprint"
      icon: "fas fa-fw fa-gavel"
      url: "/imprint/"
    - label: "Privacy Policy"
      icon: "fas fa-fw fa-user-shield"
      url: "/privacy/"
    - label: "News Feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/news/feed.xml"

scholar:
  style: ieee

# Collections
collections:
  tags:
    output: true
    permalink: /:collection/:title/
  posts:
    output: true
    permalink: /blog/:title/
  teachings:
    output: true
    permalink: /:collection/:title/
  publications:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
  news:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  # _teachings
  - scope:
      path: ""
      type: teachings
    values:
      layout: single
      read_time: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      read_time: true
      share: true
      comments: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      read_time: true
      share: true
      comments: true
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single
      read_time: true
      share: true
      comments: true
  # tags
  - scope:
      path: ""
      type: tags
    values:
      layout: tagpage
      search: false
      title-prefix: 'Tag: '
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

# Exclude & Exclude from processing.
include:
  - _pages
  - _static
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - generate-derived-files.sh
  - generate-derived-files.js
  - LICENSE

collections_dir: _pages

github: [metadata]
